parameters:
#    portfolio_main.example.class: portfolio\MainBundle\Example

services:
#    portfolio_main.example:
#        class: %portfolio_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
